FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
COPY . .
RUN go mod download
RUN go build -o main ./cloudprovider/power-manager/

FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    ca-certificates curl vim && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /app/main /app/

RUN curl -LO "https://dl.k8s.io/release/v1.32.1/bin/linux/amd64/kubectl"
RUN chmod +x ./kubectl && mv kubectl /usr/local/bin/
COPY client.crt /root/
COPY client.key /root/
COPY ca.crt /root/
COPY minconfig /root/.kube/config

ENTRYPOINT ["/app/main"]
